import Head from 'next/head'
import { FaBars } from 'react-icons/fa'

export default function Home() {
  return (
    <>
      <Head>
        <title>2eJournal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='fixed top-0 left-0 h-screen w-16 bg-gray-900 shadow'>
        <div className='w-full text-center py-2'>
          <button className='p-1 border rounded-3xl border-slate-700 hover:bg-slate-500 hover:rounded-xl transition-all duration-150 ease-linear'>
            <FaBars className='text-white inline-block' size={'25px'} />
          </button>
        </div>
      </div>
      <div className='h-screen w-screen bg-gray-700'>

      </div>
    </>
  )
}
