import Head from 'next/head'


import Skills from '../components/main_sheet/Skills';
import Sidebar from '../components/sidebar/Sidebar';

export default function Home() {
  return (
    <>
      <Head>
        <title>2eJournal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Sidebar />
      <div className='h-screen w-screen bg-gray-700'>
        <Skills />
      </div>
    </>
  )
}
